### ISSUE TITLE
Available on CRAN?

### ISSUE THREAD

**Issue by AntoineSoetewey** [goepp/aspline#10]
Dear Vivien,

This is not really an issue but I'm still asking:

My research lab only allows to install R packages that are available on CRAN.

By any chance, any idea if it will become available as a standard R package?

Regards,
Antoine

**Comment by goepp** [comment]
It's finally on CRAN: https://cran.r-project.org/package=aspline

**Comment by AntoineSoetewey** [comment]
Thanks a lot !
