### ISSUE TITLE
aridge_solver degree does not work

### ISSUE THREAD

**Issue by PursuitOfDataScience** [goepp/aspline#4]
Hi,

When I run the sample code provided in the readme, and for aridge <- aridge_solver(x, y, knots, pen, degree = 1L) no matter how I change the degree (3, 3L, 0, 1L etc.), the plot stays the same. It seems like degree does not have its play here at all. As I change degree from default value 3 to 1, I should have been expecting the lines turning out to be linear. However, that is not the case. Could you please take a look for me?

Thanks

**Comment by goepp** [comment]
Hi,

The code in the README was indeed incomplete: the degree argument was not passed on to the commands `lm` and `bSpline`:
```
a_fit <- lm(y ~ bSpline(x, knots = aridge$knots_sel[[which.min(aridge$ebic)]]))
X_seq <- bSpline(x_seq, knots = aridge$knots_sel[[which.min(aridge$ebic)]], intercept = TRUE)
`̀``
I pushed a commit that corrects this.

**Comment by goepp** [comment]
Pardon the confusion; the only pull request to consider here is [the latter](https://github.com/goepp/aspline/pull/5).
